config/routes.rb
Rails.application.routes.draw do
	devise_for :users
	
	resources :products, only: [:index] do
		resources :orders, only: :create
	end
	
	resources :orders, only: [:index, :destroy] do
		collection do
			delete 'empty_cart'
		end
	end
	
	
	resources :billings, only: [] do
		collection do
			get 'pre_pay'
			get 'execute'
		end
	end
	
	
	root 'products#index'
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/billing.rb
class Billing < ApplicationRecord
  belongs_to :user
  has_many :orders
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :product
  belongs_to :billing, optional: true

  private
  
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :orders
  has_many :users, through: :orders
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :orders
  has_many :products, through: :orders
  has_many :billings
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
	
	private
	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
	end
end

app/controllers/billings_controller.rb
class BillingsController < ApplicationController
	def pre_pay
		orders = current_user.orders.where(payed: false)
		@total = orders.pluck("price * quantity").sum()
		@items = orders.map do |order|
			item = {}
			item[:name] = order.product.name
			item[:sku] = order.id.to_s
			item[:price] = order.price.to_s
			item[:currency] = 'USD'
			item[:quantity] = order.quantity
			item
		end
		
		
		@payment = PayPal::SDK::REST::Payment.new(
		{
		:intent =>  "sale",
		:payer =>  {
		:payment_method =>  "paypal" },
		:redirect_urls => {
		:return_url => "http://localhost:3000/billings/execute",
		:cancel_url => "http://localhost:3000/" },
		:transactions =>  [{
		:item_list => {
		:items => @items },
		:amount =>  {
		:total =>  @total.to_s,
		:currency =>  "USD" },
		:description =>  "This is the payment transaction description." }]})
		
		if @payment.create
			
			#Redirige a PayPal
			redirect_url = @payment.links.find{|v| v.method == "REDIRECT" }.href
			redirect_to redirect_url
		else
			render json: payment.error
		end
		
	end
	
	
	def execute
		paypal_payment = PayPal::SDK::REST::Payment.find(params[:paymentId])
		if paypal_payment.execute(payer_id: params[:PayerID])

			amount = paypal_payment.transactions.first.amount.total
			
			billing = Billing.create(
			user: current_user,
			code: paypal_payment.id,
			payment_method: 'paypal',
			amount: amount,
			currency: 'USD'
			)
			orders = current_user.orders.where(payed: false)
			orders.update_all(payed: true, billing_id: billing.id)
			redirect_to root_path, notice: "La compra se realizó con éxito!"

		else
			render plain: "No se puedo generar el cobro en PayPal."
		end
	end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	before_action :authenticate_user!
	
	def empty_cart
		@orders = current_user.orders.where(payed: false)
		@orders.destroy_all
		redirect_to orders_path, notice: 'El carro se ha vaciado.'
	end
	
	def index
		@orders = current_user.orders.where(payed: false)
		@total = @orders.map{ |order| order.product.price * order.quantity }.sum()
		
	end
	
	
	def create
		@product = Product.find(params[:product_id])
		
		orden = Order.find_or_create_by(user: current_user, payed: false, product: @product, price: @product.price)
		orden.quantity += 1
		
		
		if orden.save
			redirect_to root_path, notice: 'EL producto ha sido agregado al carro'
		end
	end
	
	def destroy
		@order = Order.find(params[:id])
		if @order.quantity == 1
			@order.destroy
		elsif @order.quantity > 1
			new_quantity = @order.quantity - 1
			@order.update(quantity: new_quantity)
		end
		
		redirect_to orders_path, notice: 'Carro actualizado'
	end
	
	
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/billings_helper.rb
module BillingsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>CarroDeCompra</title>
	<%= csrf_meta_tags %>
	
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.1/font/css/open-iconic-bootstrap.min.css" integrity="sha256-BJ/G+e+y7bQdrYkS2RBTyNfBHpA9IuGaPmf9htub5MQ=" crossorigin="anonymous" />

	
	
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body style="padding-top:80px;">
	
	<%= render  "shared/navbar" %>
	
	
	
	<% if notice.present? %>
	<div class="alert alert-success" role="alert">
		<p class="notice"><%= notice %></p>
	</div>
	
	<% end %>
	
	
	<% if alert.present? %>
	<div class="alert alert-danger" role="alert">
		<p class="alert"><%= alert %></p>
	</div>
	
	<% end %>
	
	
	<div class="container">
		<%= yield %>
	</div>	
	
	
	
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

app/views/orders/index.html.erb
<% if @orders.count > 0 %>

<div class="row">
	<div class="col-md-5">
		<div>
			<%= link_to  "Continuar comprando", root_path, class:'btn btn-warning' %>
		</div>
	</div>

	<div class="col-md-4 offset-md-5">
			<div>
				<%= link_to  "Eliminar Carro", empty_cart_orders_path, class:'btn btn-info', method: :delete %>
			</div>
		</div>
</div>


<table class="table table-hover">
	<tr>
		<th>Producto</th>
		<th>Cantidad</th>
		<th>Precio</th>
		<th>Total</th>
		
	</tr>
	
	<% @orders.each do |order| %>
	<tr>
		<td><%= order.product.name %></td>
		<td><%= order.quantity %></td>
		<td>$<%= order.price %></td>
		<td>$<%= order.price * order.quantity %></td>
		<td> <%= link_to 'Eliminar', order_path(order), method: :delete %></td>
		
		<br>
		<% end %>
		<tr>
			<th></th>
			<th></th>
			<th>Total:</th>
			<th>   <%= @total %> </th>
		</tr>
	</tr>
	
</table>

<%= link_to 'Confirmar compra', pre_pay_billings_path, class: 'btn btn-success float-right'
%>

<% else %>
<p>No tienes productos en tu carro de compra.</p>
<% end %>

app/views/products/index.html.erb
	<h1 class="text-center bold green-text">Listado de Productos</h1>
<div class="text-right">
</div><br>


<div class="row">
	<% @products.each do |product| %>	
	<div class="col-xl-4 col-lg-6 col-md-6 col-sm-12 col-12">
		<div class="card border-success white bottom-space sombra text-center mb-4 ">
			
			<header>			
				<h3 class="grey-text bold text-center card-header"><%= product.name %></h3>
			</header>
			
			<div class="p-3 text-center">  <!-- padding de bootstrap -->
				<section>
					<div class="col-xl-6 col-lg-6 col-md-12 col-sm-12 col-12 inline-block no-padding text-center">
						<%= image_tag(product.photo, :width => 300, :height => 200) if product.photo.present? %>
					</div>
					
					<div class="col-xl-10 col-lg-6 col-md-12 col-sm-12 col-10 inline-block text-left">
						<br>
						<h3 class="green-text bold normal"> 
							Costo: 
							<span class="grey-text">
								<%= product.price %> Gs.
							</span>
						</h3>	
					</div>

						<div class="text-center">
							<%= link_to 'Agregar <i class="oi oi-cart"></i>'.html_safe, product_orders_path(product), class:'btn btn-success', method: :post %>
						</div>
						
				</section>
			</div>
		</div>
	</div>
	
	<% end %>
	
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-success fixed-top">
	<a class="navbar-brand" href="<%= root_path %>">Mi App</a>
	
	<a class="navbar-brand" href="<%= orders_path %>">Mis Ordenes</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>
	
	<div class="collapse navbar-collapse" id="navbarNav">
		<ul class="navbar-nav ml-auto">
			<% if user_signed_in? %>
			<li class="nav-item">
				<%= link_to current_user.name, "#", class: 'nav-link' %>
			</li>
			<li class="nav-item">
				<%= link_to "Cerrar Sesion", destroy_user_session_path, method: :delete, class: 'nav-link' %>
			</li>
			<% else %>
			<li class="nav-item">
				<%= link_to 'Iniciar Sesión', new_user_session_path, class: 'nav-link' %>
			</li>
			<li class="nav-item">
				<%= link_to 'Registrarse', new_user_registration_path, class: 'nav-link' %>
			</li>
			<% end %>
		</ul>
	</div>
</nav>